/**
 * Version History Timeline System
 *
 * Provides structured edit history beyond simple undo stack.
 * Stores lightweight JSON diff snapshots of page metadata and object state.
 * Never stores canvas bitmaps or full PDF buffers.
 *
 * Features:
 * - Named checkpoints (manual or auto-generated)
 * - Auto snapshots on major operations
 * - Timeline scrub preview
 * - Restore to checkpoint
 * - Memory-safe with configurable depth limit and auto-eviction
 */

import type { PageState } from '../store/pdfStore';

// ─── Types ─────────────────────────────────────────────────────

export interface TimelineEntry {
    /** Unique entry id */
    id: string;
    /** Human-readable name */
    name: string;
    /** Creation timestamp (ISO string) */
    timestamp: string;
    /** Whether this was auto-generated or manually created */
    autoGenerated: boolean;
    /** Snapshot of all page states (metadata + objects only, no bitmaps) */
    snapshot: SerializedPageState[];
    /** Optional description of what triggered this checkpoint */
    description?: string;
}

/**
 * Lightweight serialized page state — strips out canvas-heavy data.
 * Stores only the structural/object metadata needed for restore.
 */
interface SerializedPageState {
    id: string;
    pageNumber: number;
    width: number;
    height: number;
    rotation: number;
    flipX: boolean;
    flipY: boolean;
    source: 'pdf' | 'image' | 'blank';
    originalPageIndex?: number;
    backgroundColor?: string;
    /** Full objects array (position, style, text — no bitmap data) */
    objects: SerializedObject[];
}

/**
 * Serialized object — preserves all properties except large data URLs.
 * Image/stamp sources are replaced with a reference marker.
 */
interface SerializedObject {
    [key: string]: unknown;
    id: string;
    type: string;
    x: number;
    y: number;
    /** If the object had a large src/url, store a truncated marker */
    _srcTruncated?: boolean;
}

// ─── Configuration ─────────────────────────────────────────────

/** Maximum number of snapshots to retain */
const MAX_SNAPSHOTS = 50;

/** Size threshold for truncating data URLs (bytes) */
const DATA_URL_TRUNCATE_THRESHOLD = 1024;

// ─── Timeline Store (module-level singleton) ───────────────────

let timelineEntries: TimelineEntry[] = [];
const listeners: Set<() => void> = new Set();

function notifyListeners() {
    for (const listener of listeners) {
        listener();
    }
}

// ─── Serialization Helpers ─────────────────────────────────────

/**
 * Serialize a single PDFObject, truncating large data URLs to save memory.
 */
function serializeObject(obj: Record<string, unknown>): SerializedObject {
    const serialized: SerializedObject = {
        id: (obj.id as string) || '',
        type: (obj.type as string) || '',
        x: (obj.x as number) || 0,
        y: (obj.y as number) || 0
    };

    for (const [key, value] of Object.entries(obj)) {
        if (key === 'src' || key === 'url' || key === 'content') {
            // Truncate large data URLs
            if (typeof value === 'string' && value.length > DATA_URL_TRUNCATE_THRESHOLD) {
                serialized[key] = value.slice(0, 64) + '...[truncated]';
                serialized._srcTruncated = true;
            } else {
                serialized[key] = value;
            }
        } else {
            serialized[key] = value;
        }
    }

    return serialized;
}

/**
 * Serialize a PageState for snapshot storage.
 */
function serializePageState(page: PageState): SerializedPageState {
    return {
        id: page.id,
        pageNumber: page.pageNumber,
        width: page.width,
        height: page.height,
        rotation: page.rotation || 0,
        flipX: page.flipX || false,
        flipY: page.flipY || false,
        source: page.source || 'blank',
        originalPageIndex: page.originalPageIndex,
        backgroundColor: page.backgroundColor,
        objects: (page.objects || []).map(obj =>
            serializeObject(obj as unknown as Record<string, unknown>)
        ),
    };
}

// ─── Public API ────────────────────────────────────────────────

/**
 * Create a named checkpoint from the current page states.
 */
export function createCheckpoint(
    name: string,
    pages: PageState[],
    options: { autoGenerated?: boolean; description?: string } = {}
): TimelineEntry {
    const entry: TimelineEntry = {
        id: `ckpt-${Date.now()}-${Math.random().toString(36).substr(2, 6)}`,
        name,
        timestamp: new Date().toISOString(),
        autoGenerated: options.autoGenerated ?? false,
        snapshot: pages.map(serializePageState),
        description: options.description,
    };

    timelineEntries.push(entry);

    // Enforce depth limit — evict oldest auto-generated entries first
    while (timelineEntries.length > MAX_SNAPSHOTS) {
        const autoIdx = timelineEntries.findIndex(e => e.autoGenerated);
        if (autoIdx >= 0) {
            timelineEntries.splice(autoIdx, 1);
        } else {
            // All manual — evict oldest
            timelineEntries.shift();
        }
    }

    notifyListeners();
    return entry;
}

/**
 * Get all timeline entries (newest last).
 */
export function getTimeline(): TimelineEntry[] {
    return [...timelineEntries];
}

/**
 * Get a specific entry by ID.
 */
export function getEntry(id: string): TimelineEntry | undefined {
    return timelineEntries.find(e => e.id === id);
}

/**
 * Delete a specific checkpoint.
 */
export function deleteCheckpoint(id: string): boolean {
    const idx = timelineEntries.findIndex(e => e.id === id);
    if (idx >= 0) {
        timelineEntries.splice(idx, 1);
        notifyListeners();
        return true;
    }
    return false;
}

/**
 * Clear all timeline entries.
 */
export function clearTimeline(): void {
    timelineEntries = [];
    notifyListeners();
}

/**
 * Get the number of entries.
 */
export function getTimelineSize(): number {
    return timelineEntries.length;
}

/**
 * Subscribe to timeline changes.
 * Returns unsubscribe function.
 */
export function subscribe(listener: () => void): () => void {
    listeners.add(listener);
    return () => {
        listeners.delete(listener);
    };
}

/**
 * Restore a checkpoint — returns the serialized page states.
 * The caller is responsible for applying these to the PDF store.
 *
 * Returns null if the entry is not found.
 */
export function restoreCheckpoint(id: string): SerializedPageState[] | null {
    const entry = timelineEntries.find(e => e.id === id);
    if (!entry) return null;

    // Return a deep copy to prevent mutation
    return JSON.parse(JSON.stringify(entry.snapshot));
}

/**
 * Create an auto-checkpoint if the last auto-generated entry is older
 * than the specified interval (in milliseconds). Default 60 seconds.
 */
export function autoCheckpointIfNeeded(
    name: string,
    pages: PageState[],
    intervalMs = 60_000
): TimelineEntry | null {
    const lastAuto = [...timelineEntries].reverse().find(e => e.autoGenerated);

    if (lastAuto) {
        const elapsed = Date.now() - new Date(lastAuto.timestamp).getTime();
        if (elapsed < intervalMs) return null;
    }

    return createCheckpoint(name, pages, { autoGenerated: true });
}

/**
 * Format a timestamp for display.
 */
export function formatTimestamp(iso: string): string {
    const date = new Date(iso);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);

    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;

    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24) return `${diffHours}h ago`;

    return date.toLocaleDateString(undefined, { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' });
}
