import React, { useState, useCallback, useEffect } from 'react';
import { X, Clock, Plus, RotateCcw, Trash2, Flag, Zap } from 'lucide-react';
import { usePDFStore } from '../../../store/pdfStore';
import type { PageState } from '../../../store/pdfStore';
import {
    createCheckpoint,
    getTimeline,
    deleteCheckpoint,
    restoreCheckpoint,
    clearTimeline,
    subscribe,
    formatTimestamp,
} from '../../../utils/versionTimeline';
import type { TimelineEntry } from '../../../utils/versionTimeline';

interface TimelineModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const TimelineModal: React.FC<TimelineModalProps> = ({ isOpen, onClose }) => {
    const theme = usePDFStore(s => s.theme);
    const pages = usePDFStore(s => s.pages);

    const [entries, setEntries] = useState<TimelineEntry[]>(getTimeline());
    const [newCheckpointName, setNewCheckpointName] = useState('');
    const [confirmRestore, setConfirmRestore] = useState<string | null>(null);
    const [restoredId, setRestoredId] = useState<string | null>(null);

    // Subscribe to timeline changes
    useEffect(() => {
        if (!isOpen) return;
        // Updated state already during init or via subscribe
        const unsub = subscribe(() => setEntries(getTimeline()));
        return unsub;
    }, [isOpen]);

    const handleCreateCheckpoint = useCallback(() => {
        const name = newCheckpointName.trim() || `Checkpoint ${entries.length + 1}`;
        createCheckpoint(name, pages);
        setNewCheckpointName('');
    }, [newCheckpointName, pages, entries.length]);

    const handleRestore = useCallback((entryId: string) => {
        const snapshot = restoreCheckpoint(entryId);
        if (!snapshot) return;

        try {
            // Create a safety checkpoint before restoring
            createCheckpoint('Before Restore', pages, {
                autoGenerated: true,
                description: 'Auto-saved before timeline restore',
            });

            // Apply snapshot to PDF store
            // We need to update each page's objects. The snapshot contains
            // serialized page states — we apply objects back to matching pages.
            const store = usePDFStore.getState();
            const currentPages = store.pages;

            const updatedPages: PageState[] = snapshot.map(snap => {
                const existing = currentPages.find(p => p.id === snap.id);
                if (existing) {
                    return {
                        ...existing,
                        objects: snap.objects.map(obj => {
                            // Remove serialization markers
                            const cleaned = { ...obj };
                            delete cleaned._srcTruncated;
                            return cleaned;
                        }),
                        rotation: snap.rotation,
                        flipX: snap.flipX,
                        flipY: snap.flipY,
                        backgroundColor: snap.backgroundColor,
                    } as unknown as PageState;
                }
                // Page doesn't exist in current state — skip or create blank
                return {
                    id: snap.id,
                    pageNumber: snap.pageNumber,
                    width: snap.width,
                    height: snap.height,
                    rotation: snap.rotation,
                    flipX: snap.flipX,
                    flipY: snap.flipY,
                    source: snap.source,
                    originalPageIndex: snap.originalPageIndex,
                    backgroundColor: snap.backgroundColor,
                    objects: snap.objects.map(obj => {
                        const cleaned = { ...obj };
                        delete cleaned._srcTruncated;
                        return cleaned;
                    }),
                    paths: [],
                } as unknown as PageState;
            });

            // Batch update pages
            usePDFStore.setState({ pages: updatedPages });

            setRestoredId(entryId);
            setConfirmRestore(null);
            setTimeout(() => setRestoredId(null), 2000);
        } catch (err) {
            console.error('Timeline restore failed:', err);
            setConfirmRestore(null);
        }
    }, [pages]);

    const handleDelete = useCallback((id: string) => {
        deleteCheckpoint(id);
    }, []);

    const handleClearAll = useCallback(() => {
        if (confirm('Clear all timeline checkpoints?')) {
            clearTimeline();
        }
    }, []);

    if (!isOpen) return null;

    const isDark = theme === 'dark';
    const reversedEntries = [...entries].reverse(); // newest first

    return (
        <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
            <div className={`relative w-full max-w-lg max-h-[80vh] mx-4 rounded-2xl overflow-hidden flex flex-col ${isDark ? 'bg-[#1e1e22] text-white' : 'bg-white text-gray-900'}`}>
                {/* Header */}
                <div className={`flex items-center justify-between px-6 py-4 border-b ${isDark ? 'border-white/10' : 'border-gray-200'}`}>
                    <div className="flex items-center gap-3">
                        <Clock size={20} className="text-amber-400" />
                        <h2 className="text-lg font-bold">Version Timeline</h2>
                        <span className={`text-xs px-2 py-0.5 rounded-full ${isDark ? 'bg-white/10 text-zinc-400' : 'bg-gray-100 text-gray-500'}`}>
                            {entries.length} checkpoint{entries.length !== 1 ? 's' : ''}
                        </span>
                    </div>
                    <button
                        onClick={onClose}
                        className={`p-2 rounded-lg transition-colors ${isDark ? 'hover:bg-white/10' : 'hover:bg-gray-100'}`}
                    >
                        <X size={18} />
                    </button>
                </div>

                {/* Create Checkpoint */}
                <div className={`px-6 py-3 border-b ${isDark ? 'border-white/10' : 'border-gray-200'}`}>
                    <div className="flex items-center gap-2">
                        <input
                            type="text"
                            value={newCheckpointName}
                            onChange={(e) => setNewCheckpointName(e.target.value)}
                            onKeyDown={(e) => e.key === 'Enter' && handleCreateCheckpoint()}
                            placeholder="Checkpoint name..."
                            className={`flex-1 px-3 py-2 rounded-lg text-sm focus:outline-none ${isDark
                                ? 'bg-white/5 border border-white/10 text-white placeholder:text-zinc-600 focus:border-amber-500/50'
                                : 'bg-gray-50 border border-gray-200 text-gray-900 placeholder:text-gray-400 focus:border-amber-500'
                                }`}
                        />
                        <button
                            onClick={handleCreateCheckpoint}
                            disabled={pages.length === 0}
                            className="px-4 py-2 bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-600 hover:to-orange-700 disabled:opacity-40 text-white text-xs font-bold rounded-lg transition-all flex items-center gap-1.5 shadow-lg"
                        >
                            <Plus size={14} />
                            Save
                        </button>
                    </div>
                </div>

                {/* Timeline List */}
                <div className="flex-1 overflow-y-auto px-6 py-3">
                    {reversedEntries.length === 0 ? (
                        <div className="text-center py-12">
                            <Clock size={40} className={isDark ? 'text-zinc-700 mx-auto mb-3' : 'text-gray-300 mx-auto mb-3'} />
                            <p className={`text-sm font-semibold ${isDark ? 'text-zinc-500' : 'text-gray-400'}`}>
                                No checkpoints yet
                            </p>
                            <p className={`text-xs mt-1 ${isDark ? 'text-zinc-600' : 'text-gray-400'}`}>
                                Create a checkpoint to save your current state
                            </p>
                        </div>
                    ) : (
                        <div className="space-y-2">
                            {reversedEntries.map((entry, idx) => (
                                <div
                                    key={entry.id}
                                    className={`relative flex items-start gap-3 p-3 rounded-xl border transition-all ${restoredId === entry.id
                                        ? isDark ? 'bg-green-500/10 border-green-500/30' : 'bg-green-50 border-green-200'
                                        : confirmRestore === entry.id
                                            ? isDark ? 'bg-amber-500/10 border-amber-500/30' : 'bg-amber-50 border-amber-200'
                                            : isDark ? 'bg-white/[0.02] border-white/5 hover:border-white/10' : 'bg-gray-50 border-gray-100 hover:border-gray-200'
                                        }`}
                                >
                                    {/* Timeline dot */}
                                    <div className="flex flex-col items-center pt-1">
                                        <div className={`w-3 h-3 rounded-full ${entry.autoGenerated
                                            ? 'bg-zinc-600 border border-zinc-500'
                                            : 'bg-amber-500 border border-amber-400 shadow-sm shadow-amber-500/30'
                                            }`} />
                                        {idx < reversedEntries.length - 1 && (
                                            <div className={`w-px h-8 mt-1 ${isDark ? 'bg-white/10' : 'bg-gray-200'}`} />
                                        )}
                                    </div>

                                    {/* Content */}
                                    <div className="flex-1 min-w-0">
                                        <div className="flex items-center gap-2">
                                            {entry.autoGenerated ? (
                                                <Zap size={12} className="text-zinc-500" />
                                            ) : (
                                                <Flag size={12} className="text-amber-400" />
                                            )}
                                            <span className="text-sm font-semibold truncate">{entry.name}</span>
                                        </div>
                                        <div className={`text-[10px] mt-0.5 ${isDark ? 'text-zinc-500' : 'text-gray-400'}`}>
                                            {formatTimestamp(entry.timestamp)} • {entry.snapshot.length} page{entry.snapshot.length !== 1 ? 's' : ''}
                                            {entry.description && ` • ${entry.description}`}
                                        </div>

                                        {/* Confirm restore UI */}
                                        {confirmRestore === entry.id && (
                                            <div className="mt-2 flex items-center gap-2 animate-in fade-in duration-200">
                                                <span className={`text-[11px] ${isDark ? 'text-amber-300' : 'text-amber-600'}`}>
                                                    Restore to this checkpoint?
                                                </span>
                                                <button
                                                    onClick={() => handleRestore(entry.id)}
                                                    className="px-2.5 py-1 bg-amber-600 hover:bg-amber-500 text-white text-[10px] font-bold rounded-md"
                                                >
                                                    Confirm
                                                </button>
                                                <button
                                                    onClick={() => setConfirmRestore(null)}
                                                    className={`px-2.5 py-1 text-[10px] font-bold rounded-md ${isDark ? 'bg-white/10 text-zinc-400' : 'bg-gray-200 text-gray-500'}`}
                                                >
                                                    Cancel
                                                </button>
                                            </div>
                                        )}

                                        {restoredId === entry.id && (
                                            <div className="mt-1 text-[11px] text-green-400 font-semibold animate-in fade-in">
                                                ✓ Restored successfully
                                            </div>
                                        )}
                                    </div>

                                    {/* Actions */}
                                    {confirmRestore !== entry.id && (
                                        <div className="flex items-center gap-1 shrink-0">
                                            <button
                                                onClick={() => setConfirmRestore(entry.id)}
                                                className={`p-1.5 rounded-md transition-colors ${isDark ? 'hover:bg-white/10 text-zinc-500 hover:text-amber-400' : 'hover:bg-gray-200 text-gray-400 hover:text-amber-600'}`}
                                                title="Restore"
                                            >
                                                <RotateCcw size={14} />
                                            </button>
                                            <button
                                                onClick={() => handleDelete(entry.id)}
                                                className={`p-1.5 rounded-md transition-colors ${isDark ? 'hover:bg-red-500/10 text-zinc-500 hover:text-red-400' : 'hover:bg-red-50 text-gray-400 hover:text-red-500'}`}
                                                title="Delete"
                                            >
                                                <Trash2 size={14} />
                                            </button>
                                        </div>
                                    )}
                                </div>
                            ))}
                        </div>
                    )}
                </div>

                {/* Footer */}
                {entries.length > 0 && (
                    <div className={`px-6 py-3 border-t ${isDark ? 'border-white/10' : 'border-gray-200'}`}>
                        <button
                            onClick={handleClearAll}
                            className={`text-[10px] font-semibold transition-colors ${isDark ? 'text-zinc-600 hover:text-red-400' : 'text-gray-400 hover:text-red-500'}`}
                        >
                            Clear All Checkpoints
                        </button>
                    </div>
                )}
            </div>
        </div>
    );
};
